name: Deploy

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Version
        run: echo "Promoting version: ${{ inputs.version }}"
        
