on:
  workflow_dispatch:
  workflow_run:
    types: [completed]
    workflows:
      - Build
    branches:
      - deploy

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        integration-test: ["dev"]

    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Integration-test
        run: |
          echo "${{matrix.integration-test}}"

      - name: Random sleep before installing dependencies
        run: |
          SECONDS=$((RANDOM % 10 + 5))
          echo "Sleeping for $SECONDS seconds before npm ci..."
          sleep $SECONDS

      - name: Install dependencies
        run: npm ci
