name: Reusable Workflow

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      ACCESS_TOKEN:
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello, ${{ inputs.username }}!"
      
      - name: Access secret
        run: |
          echo "Using secret token: ${{ secrets.ACCESS_TOKEN }}"
