# .github/workflows/caller-workflow.yml
name: Caller Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable:
    uses: ./.github/workflows/deploy.yml
    with:
      username: "Ashutosh"
    secrets:
      ACCESS_TOKEN: "asdhfoaiusdfhoa"
