name: Basic

on:
  push:
    branches:
      - "**"

  workflow_dispatch:
    inputs:
      runRspec:
        description: "Force Rspec run"
        required: true
        default: true
        type: boolean

      runContainerScan:
        description: "Force Container Scan"
        required: true
        default: true
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RUN_RSPEC: ${{ github.event.inputs.runRspec || true }}
      RUN_CONTAINER_SCAN: ${{ github.event.inputs.runContainerScan || true}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print all inputs
        run: |
          echo "runRspec: ${{ github.event.inputs.runRspec }}"
          echo "runContainerScan: ${{ github.event.inputs.runContainerScan }}"
          echo "RUN_RSPEC: ${{ env.RUN_RSPEC }}"
          echo "RUN_CONTAINER_SCAN: ${{ env.RUN_CONTAINER_SCAN }}"
