name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Version
        run: echo "VER_REL=1.0-${{ github.run_number }}" >> $GITHUB_ENV

      - name: Call Promote Workflow
        uses: ./.github/workflows/deploy.yml
        with:
          version: ${{ env.VER_REL }}
